### ISSUE TITLE
Using local image as base image does not work

### ISSUE THREAD

**Issue by archonandrewhunt** [dotnet/sdk-container-builds#195]
I have a simple build process in place where a base image is built and tagged as "name:tag" where name is of the form "proj.name" and tag is a semver version.

When I run the publish to container with this base image specified I always receive an error `microsoft.net.build.containers\0.1.8\build\Microsoft.NET.Build.Containers.targets(45,9): error : Could not parse FullyQualifiedBaseImageName: 0`. The base image is being set through command line property like so: `/property:ContainerBaseImage=name:tag`

I'm at a loss at this point to understand what I'm doing wrong. Any help you can offer would be appreciated.

**Comment by baronfel** [comment]
There's a bunch of build logic happening, but what would help the most is a bin log of the publish operation. You can learn about them and how to have the publish command make them for you at [aka.ms/binlog](aka.ms/binlog). 

If that's not possible, then knowing the exact value specified for the `ContainerBaseImage` property would let us run the logic in the parse target to see what went wrong.

**Comment by archonandrewhunt** [comment]
To start with, here's an example base image name I've just tested that runs into this issue: `/property:ContainerBaseImage=proj.name.base:2022.1007.1`

Let me review the binlog to make sure I'm good to share that publicly.

**Comment by archonandrewhunt** [comment]
Thanks for the suggestion, but that doesn't seem to work either. That said the error is different:

``` error MSB4018: The "ParseContainerProperties" task failed unexpectedly.
 error MSB4018: System.UriFormatException: Invalid URI: Invalid port specified.
 error MSB4018:    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions) 
 error MSB4018:    at System.Uri..ctor(String uriString, UriKind uriKind) 
 error MSB4018:    at Microsoft.NET.Build.Containers.ContainerHelpers.ContainerImageToUri(String containerBase)
 error MSB4018:    at Microsoft.NET.Build.Containers.ContainerHelpers.TryParseFullyQualifiedContainerName(String fullyQualifiedContainerName, String& containerRegistry, String& containerName, String& containerTag) 
 error MSB4018:    at Microsoft.NET.Build.Containers.Tasks.ParseContainerProperties.Execute() 
 error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
 error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) ```

Now it seems to be trying to parse the version tag as a port number.

**Comment by baronfel** [comment]
I think we've got a good enough idea of what's going on here now. I think this scenario is fairly broken at the moment unless you do the following:
* prepend docker:// to your image name, and
* ensure that your tag is an int under the port limit

in other words, the workaround is horrible and bad and we should feel bad.  We'll likely have to move away from piggy-backing on Uri-based validation for image names, which is a good thing to do, in order to unblock the scenario.

**Comment by archonandrewhunt** [comment]
I actually don't know if that workaround works. I just tried with `-p:ContainerBaseImage=docker://projnamebase:1` and I'm back to the original error I posted in the OP.

In any case, thanks for acknowledging. I know this is prerelease at the moment so no harm done. I'll look forward to a fix for this scenario.

**Comment by baronfel** [comment]
This is a pretty big scenario so we should try to unblock it before the next release (anticipated next week-ish?). Using a local image (possibly built from a local Dockerfile) is our escape hatch for when users have needs that this tech can't solve - for example needing to create a specific user via `useradd` or install packages via the system package manager. Right now we can't solve that need, which we should treat as a blocker.

**Comment by SeppPenner** [comment]
This is something I could also need. We have Docker containers that need to install some dependencies in order to be able to show PDF reports correctly (e.g. `RUN apt-get install -y libc6-dev libicu-dev libharfbuzz0b libfontconfig1 libfreetype6` on Debian). Is there a new ETA when this might be testable?

**Comment by baronfel** [comment]
Hey, sorry about the delay here. We haven't solved this yet, and it's been on the back-burner a bit in favor of expanding our authenticated registry support and working on support for RIDs other than linux-64.

I think the main problem here is that local-Docker images have a different manifest and config format, and we'd need to teach the library how to translate between the formats.

**Comment by kimcu-on-thenet** [comment]
Possible workaround:

1. [Run a local registry](https://docs.docker.com/registry/deploying/)

```bash
docker run -d -p 5000:5000 --restart=always --name registry registry:2
```
2. Build your own base image then push to this local registry

```bash
docker build -t localhost:5000/image-base:latest -f Dockerfile .

docker image push localhost:5000/image-base:latest
```

3. Configure your `csproj` file by

```xml
<PropertyGroup>
<ContainerBaseImage>localhost:5000/image-base:latest</ContainerBaseImage>
</PropertyGroup>
```

**Comment by sliekens** [comment]
I am in the process of converting a solution with docker compose and a lot of custom Dockerfiles to an Aspire solution, and I wanted to take this opportunity to try out the SDK container build tooling. It turns out that I will have to back out of this improvement until I can point `ContainerBaseImage` to a local base image. The custom Dockerfiles contain too many customizations like `COPY --from=x` and `RUN x` that are not supported by the SDK tools.

I considered pushing the custom base image to a "staging" registry, but anyway that's a silly workaround and would slow down the build. Not to mention possible versioning conflicts when concurrent build agents push and pull from and to the staging registry.

**Comment by benlongo** [comment]
Is this still a good place to track this issue now that things have been moved? This limitation is still quite frustrating.

**Comment by pvanbuijtene** [comment]
Also running into this, luckily I can host the image in a registry but would also prefer to handle this locally.
